add_newline = false

format = """
[󰣇 ](#ff69b4)$directory$git_branch$git_status$character
"""

[directory]
truncation_length = 3

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
